name: run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-n-test:
    name: Install and test the package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install the package locally
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Install the dependencies
      run: |
        python -m pip install pytest
    - name: Run tests
      run: |
        pytest run_tests/ -v
