name: unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-n-test:
    name: Install and test the package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install the package locally
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Install the dependencies
      run: |
        python -m pip install pytest coverage black
    - name: Generate coverage data
      run: |
        coverage run -m pytest tests
        coverage report
        coverage xml
    - name: Test with pytest
      run: |
        pytest
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
    - name: Check code format
      run: |
        black --check .
